### ISSUE TITLE
Model implementation 

### ISSUE THREAD

**Issue by mrbacky** [mrbacky/ChillTV#19]
Where to put OBS lists - Controller or Model?
in Model we should use Arraylists? 
CONTROLLER - use OBS lists OR addListener?

**Comment by Chililove** [comment]
I know now that an observable list and addListener is kinda the same. The difference is:
addListener can "listen" from outside the code and observable can "listen" inside the code. Both can be used in this project as far as I'm concerned.

**Comment by Chililove** [comment]
the obs lists is put in the model. - not controller.
and in model we can use arraylists, yes. 

Hope this is any help, do not know if you already answered these questions yourself.

**Comment by mrbacky** [comment]
We are confused about our feedback so we will ask Jeppe tomorrow morning.
